// LVGL 8.4.0 configuration for SigenStorPuck.
//
// This is deliberately a *partial* config, not a copy of lv_conf_template.h.
// LVGL's lv_conf_internal.h guards every option with #ifndef and supplies a
// default, so only the settings this project actually changes appear here —
// which keeps the diff meaningful when LVGL is upgraded.
//
// Found via -D LV_CONF_INCLUDE_SIMPLE (see platformio.ini); PlatformIO puts
// include/ on the global include path, so the sim environment picks up the same
// file with no extra plumbing.

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

// ---------------------------------------------------------------- colour ----

// RGB565. draw16bitRGBBitmap() (used by every Arduino_GFX panel, CO5300 or
// this board's ST7701) wants native byte order, so no byte swap.
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

// ---------------------------------------------------------------- memory ----

// LVGL's own object/style pool. Large bitmaps are allocated separately in PSRAM
// rather than being sized into this (docs/PLAN.md §B1).
//
// On the device the pool itself now lives in PSRAM too — see puck_lv_mem.h for
// why, which is a story about the TLS handshake rather than about LVGL. There is
// no LV_MEM_SIZE on that path: the pool grows into 8 MB instead of being reserved
// out of 320 KB.
//
// The simulator keeps LVGL's own allocator, so `--shot` can still report how full
// the pool would be. It needed 96 KB once there were six screens: 64 KB no longer
// covered six screens' objects and styles plus the two QR canvases (~5.7 KB of
// 1-bit indexed image between them), and the way it failed is worth knowing —
// the pool does not report itself full, it fails inside whatever asks for memory
// next. Here that was circ_calc_aa4, the anti-aliased corner mask behind a
// rounded rectangle, asserting "Out of memory" on a 9 px radius it had drawn a
// hundred times before.
#if defined(ARDUINO)
#define LV_MEM_CUSTOM 1
#define LV_MEM_CUSTOM_INCLUDE "puck_lv_mem.h"
#define LV_MEM_CUSTOM_ALLOC puck_lv_malloc
#define LV_MEM_CUSTOM_FREE puck_lv_free
#define LV_MEM_CUSTOM_REALLOC puck_lv_realloc
#else
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (96U * 1024U)
#endif

// ------------------------------------------------------------------ time ----

// Drive LVGL's clock from the host's own millisecond counter instead of calling
// lv_tick_inc() from a timer interrupt — one less thing to get wrong, and the
// network task in §B3 cannot starve it.
#define LV_TICK_CUSTOM 1
#if defined(ARDUINO)
#define LV_TICK_CUSTOM_INCLUDE "Arduino.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())
#else
// sim environment: same LVGL, same config, SDL's clock. Unqualified "SDL.h"
// because sdl2-config --cflags puts the SDL2 directory itself on the path.
#define LV_TICK_CUSTOM_INCLUDE "SDL.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (SDL_GetTicks())
#endif

// ~60 Hz. The RGB panel is continuously scanned at its own pixel clock
// regardless (see PUCK_LCD_PCLK_HZ in board_config.h) — this just paces how
// often LVGL re-renders into the draw buffer LVGL owns.
#define LV_DISP_DEF_REFR_PERIOD 16
#define LV_INDEV_DEF_READ_PERIOD 16

// --------------------------------------------------------------- geometry ----

// Guition ESP32-4848S040: 480 px across a 4.3" panel, ~130 px my old 1.75"
// board (466 px) target was tuned for the same DPI it had — this is now
// closer to the physical ~130 px/in this board's own panel would want if it
// weren't smaller. 480 px / 4.3 in comes out to roughly 112, which is what's
// set below; nudge it if paddings/fonts read too airy or too tight compared
// with how the screens were designed.
#define LV_DPI_DEF 112

// ----------------------------------------------------------------- fonts ----

// Our own Montserrat subsets from src/ui/fonts/, generated by
// tools/generate_fonts.sh. Same typeface and weight as LVGL's built-ins, but
// they also carry "£", "°" and "·" — LVGL's stock fonts are ASCII-only, and the
// Puck shows a saving in pounds and a cell temperature in degrees.
//
// The built-ins stay off: carrying two near-identical Montserrats would waste
// flash and make it easy to reach for the one that cannot render a pound sign.
#define LV_FONT_CUSTOM_DECLARE \
  LV_FONT_DECLARE(puck_font_14) \
  LV_FONT_DECLARE(puck_font_20) \
  LV_FONT_DECLARE(puck_font_28) \
  LV_FONT_DECLARE(puck_font_48)

#define LV_FONT_DEFAULT &puck_font_20

// --------------------------------------------------------------- widgets ----

// LVGL's own QR encoder, for the settings-page address on screen 5 and on the
// "Not configured" overlay. Off by default in lv_conf_internal.h. It draws into
// a 1-bit indexed canvas out of LV_MEM_SIZE, which is a couple of KB at the
// sizes used here — cheaper than carrying a second encoder, and it means the
// simulator renders exactly what the device does.
#define LV_USE_QRCODE 1

// ----------------------------------------------------------------- debug ----

// LVGL's own warnings go to the USB-CDC serial log. Raise to _INFO while
// chasing a layout problem.
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

#endif  // LV_CONF_H
